name: gamesroom
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-378.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  dynamic_color: ^1.6.3
  loading_animation_widget: ^1.2.0+4
  google_mobile_ads: ^2.4.0
  material_color_utilities: ^0.2.0
  google_fonts: ^4.0.3
  firebase_core: ^2.9.0
  random_text_reveal: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  fonts:
  - family: lcddot
    fonts:
    - asset: assets/fonts/lcddot_tr.ttf